import pandas as pd


"""
create operation
"""


create_prompts = {
    "xsum":(
        "You are a news writer tasked with continuing a news article based on the following context:\n"
        "{text_first_part}\n\n"
        "Your objective is to continue this news article in a manner that is consistent with the tone, style, and atmosphere of the provided context. The continuation should:\n"
        "Seamlessly transition from the provided context into the next part of the article.\n"
        "Develop the content logically, adding depth to the topic, and maintaining the factual and engaging tone established.\n"
        "Ensure there are no repetitions or restatements of the original sentences. Focus solely on generating the new continuation.\n"
        "Maintain a high level of writing quality, ensuring that the text is grammatically correct, well-structured, and engaging.\n"
        "Ensure the continuation is consistent with the overall theme and style of the input.\n"
        "Your polishing needs to conform to the standards and expressions of news article.\n"
        "The continuation should be within {word_number} letters in length.\n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Output only the continuation of the news article.\n"
        "Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed, coherent, and compelling continuation, staying within the specified word limit."
    ),
    "writingprompts":(
        "You are a professional writer tasked with continuing a narrative based on the following context:\n"
        "{text_first_part}\n\n"
        "Your objective is to continue this story in a manner that is consistent with the tone, style, and atmosphere of the provided context. The continuation should:\n"
        "Seamlessly transition from the provided context into the next part of the story.\n"
        "Develop the narrative logically, adding depth to the setting, introducing new elements (such as characters, events, or conflict), and maintaining the mood established.\n"
        "Ensure there are no repetitions or restatements of the original sentences. Focus solely on generating the new continuation.\n"
        "Maintain a high level of writing quality, ensuring that the text is grammatically correct, well-structured, and engaging.\n"
        "Ensure the continuation is consistent with the overall theme and style of the input.\n"
        "Your polishing needs to conform to the standards and expressions of creative writing.\n"
        "The continuation should be within {word_number} letters in length. \n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Output only the continuation of the story. Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed, coherent, and compelling continuation, staying within the specified word limit."
    ),
    "pubmedqa":(
        "You are a biomedical researcher tasked with continuing an academic abstract based on the following context:\n"
        "{text_first_part}\n\n"
        "Your objective is to continue this academic abstract in a manner that is consistent with the tone, style, and atmosphere of the provided context. The continuation should:\n"
        "Seamlessly transition from the provided context into the next part of the paper.\n"
        "Develop the content logically, adding depth to the topic, and maintaining the formal and scientific tone established.\n"
        "Ensure there are no repetitions or restatements of the original sentences. Focus solely on generating the new continuation.\n"
        "Maintain a high level of writing quality, ensuring that the text is grammatically correct, well-structured, and scientifically rigorous.\n"
        "Ensure the continuation is consistent with the overall theme and style of the input.\n"
        "Your polishing needs to conform to the standards and expressions of biomedical academic abstract.\n"
        "The continuation should be within {word_number} letters in length.\n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Output only the continuation of the academic paper.\n"
        "Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed, coherent, and scientifically accurate continuation, staying within the specified word limit."
    ),
    "squad":(
        "You are a Wikipedia editor tasked with continuing an article based on the following context:\n"
        "{text_first_part}\n\n"
        "Your objective is to continue this article in a manner that is consistent with the tone, style, and atmosphere of the provided context. The continuation should:\n"
        "Seamlessly transition from the provided context into the next part of the article.\n"
        "Develop the content logically, adding depth to the topic, and maintaining the encyclopedic tone established.\n"
        "Ensure there are no repetitions or restatements of the original sentences. Focus solely on generating the new continuation.\n"
        "Maintain a high level of writing quality, ensuring that the text is grammatically correct, well-structured, and engaging.\n"
        "Ensure the continuation is consistent with the overall theme and style of the input.\n"
        "Your polishing needs to conform to the standards and expressions of wikipedia article.\n"
        "The continuation should be within {word_number} letters in length.\n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Output only the continuation of the article.\n"
        "Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed, coherent, and compelling continuation, staying within the specified word limit."
    ),
    "openreview":(
        "You are a reviewer on OpenReview tasked with writing a review comment based on the following context:\n"
        "{text_first_part}\n\n"
        "Your objective is to complete the remaining part of the review in a manner that is consistent with the tone, style, and atmosphere of the provided context. The continuation should:\n"
        "1. Seamlessly transition from the provided context into the next part of the review.\n"
        "2. the feedback should include new points, and maintaining the professional tone established.Please provide feedback in a structured, point-by-point format.\n"
        "3. Ensure there are no repetitions or restatements of the original sentences. Focus solely on generating the new continuation.\n"
        "4. Maintain a high level of writing quality, ensuring that the text is grammatically correct, well-structured, and constructive.\n"
        "5. Ensure the continuation is consistent with the overall theme and style of the input.\n"
        "6. The continuation should be  within {word_number} words in length.\n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Output only the continuation of the review.\n"
        "Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed, coherent, and constructive continuation, staying within the specified word limit."
    ),
    "blog":(
        "You are a blogger tasked with continuing a blog post based on the following context:\n"
        "{text_first_part}\n\n"
        "Your task is to continue the blog post in a way that matches the tone, style, and theme of the provided context. Follow these guidelines:\n"
        "Start naturally from the provided context and expand on it.\n"
        "Add new ideas or perspectives to develop the topic further.\n"
        "Avoid repeating or restating the original content.\n"
        "Keep the writing clear, engaging, and grammatically correct.\n"
        "Ensure the continuation fits the overall theme and style of the input.\n"
        "The continuation should be around {word_number} letters in length.\n\n"
        "Output only the continuation of the blog post.\n"
        "Do not repeat or paraphrase any part of the given context.\n"
        "Provide a detailed and coherent continuation within the specified word limit."
    ),
    "tweets": (
        "You are a Twitter user tasked with continuing a narrative based on the following snippet. Your tweet must meet the following requirements:\n"
        "1. Keep it under 50 words.\n"
        "2. Maintain the tone, style, and atmosphere of the snippet.\n"
        "3. Seamlessly transition from the snippet without repetition or paraphrasing.\n"
        "4. Introduce new elements (e.g., characters, events, or conflict) to advance the narrative.\n\n"
        "Snippet:\n"
        "{text_first_part}\n\n"
        "Output only the continuation of the tweet without additional explanations.\n"
        "Do not repeat or paraphrase any part of the given context. \n"
    )
}


"""
polish operation
"""

polish_prompts = {
    "xsum":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of news writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "writingprompts":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of creative writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "pubmedqa":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of academic abstract.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "squad":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of wikipedia article.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "openreview":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of academic review comments.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "blog":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of blog.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "**Important Note:** The content generated is purely fictional and intended for creative or educational purposes only. It does not contain any harmful, violent, or inappropriate material, nor does it promote any negative or harmful behavior.\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    ),
    "tweets":(
        "Text polishing refers to the process where, after inputting text, the model improves the quality, fluency, "
        "and accuracy of the given text to make it more in line with linguistic standards and reader expectations. "
        "This involves correcting grammatical mistakes, enhancing the way ideas are expressed, and adjusting word choice, "
        "to enhance the clarity, logic, and readability of the text.\n\n"
        "I currently have an article that I need your help to polish. "
        "Your polishing needs to conform to the standards and expressions of tweets.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, you only need to output your polished text. "
        "Do not include any extra information such as titles, comments, or additional notes at the beginning or end. "
        "Just focus on providing the polished content only. "
        "DO NOT GENERATE ANY SENTENCE LIKE 'HERE IS THE POLISHED TEXT' OR 'CERTAINLY IS THE POLISHED TEXT' etc. !!\n\n"
        "DO NOT RETURN EMPTY STRING!!!!"
    )
}

"""
translate operation
"""

translate_prompts = {
    "trans_to_ch":(
        "Translate the following English text into Chinese. \n"
        "Please return only the translated Chinese text, without any additional commentary or explanation.\n"
        "The text is as follows:\n"
        "{context}\n\n"
    ),
    "trans_to_en":(
        "Translate the following Chinese text into English. \n"
        "Please return only the translated English text, without any additional commentary or explanation.\n"
         "The text is as follows:\n"
        "{context}\n\n"
    ),
}

"""
refine operation
"""
refine_prompts = {
    "xsum":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have a news article that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of news writing.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "writingprompts":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have an article that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of creative writing.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "pubmedqa":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have an article that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of academic abstract.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "squad":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have a wikipedia article that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of wikipedia article.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "openreview":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have a openreview comment that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of academic review comments.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "blog":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"

        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have a blog that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of blog writing.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    ),
    "tweets":(
        "Text refining refers to the process where, after inputting text, the language model simplifies, compresses, "
        "or rewrites the given content into a version that is more concise, clear, and easier to understand. "
        "It removes unnecessary repetitions, verbose sections, or irrelevant parts while preserving all key information "
        "and the original meaning. The goal of refinement is not to shorten arbitrarily or to extract only the main points, "
        "but to retain the full substance of the original text in a more polished and readable form.\n\n"
        "Refinement is different from summarization. Summarization rewrites the input into a shorter abstract that only includes "
        "the main ideas or key points, possibly omitting details. In contrast, refinement keeps all original content intact in meaning, "
        "but makes it more concise and fluent by reducing redundancy and improving structure.\n\n"
        
        "The refined text must be shorter than the original text. "
        "Do not simply paraphrase or reorder the original content without reducing its length.\n\n"
        "I have a tweet that needs refining. Your task is to refine the text according to the above principles.\n\n"
        "Your refining needs to conform to the standards and expressions of tweets.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the refined text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the refined text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the refined content only."
    )
}

"""
summary operation
"""
summary_prompts = {
    "xsum": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have a news article that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "writingprompts": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have an article that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "pubmedqa": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have an article that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "squad": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have a wikipedia article that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "openreview": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have a openreview comment that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "blog": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have a blog that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    ),
    "tweets": (
        "Text summarization refers to the process where, after inputting text, the language model generates a concise and accurate abstract "
        "that highlights the main ideas and key points. The goal of summarization is to improve reading efficiency and support quick understanding "
        "by reducing the amount of text while preserving the essential content. The summary should be significantly shorter than the original text "
        "and should not include unnecessary details or redundant information.\n\n"
        "Summarization is different from refinement. Refinement improves the clarity and fluency of the original text without omitting any key information. "
        "In contrast, summarization omits secondary details and focuses only on conveying the core ideas of the original content.\n\n"
        "The summary must be substantially shorter than the original text. Do not copy or slightly modify the original sentences. "
        "Instead, rephrase and condense the content to emphasize the main points only.\n\n"

        "The summarized text must be shorter than the original text. "
        "I have a tweet that needs summarizing. Your task is to summarize the text according to the above principles.\n\n"

        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the summarized text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the summarized text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the summarized content only."
    )
}

"""
rewrite operation
"""
rewrite_prompts = {
    "xsum": (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"
        
        "I have a news article that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of news writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'writingprompts': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have a creative writing article that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of creative writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'pubmedqa': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have an article that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of academic abstract.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'squad': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have a wikipedia article that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of news writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'openreview': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have a openreview comment that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of review comments.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'blog': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have a blog that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of blog writing.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    ),
    'tweets': (
        "Text rewriting refers to the process in which, upon receiving a text input, the language model adjusts word choices, "
        "reorganizes sentence structures, and transforms paragraph flow to change the style of the original text. "
        "The resulting version should retain the core meaning and themes while expressing them in a different way. "
        "The goal is to enhance readability, fluidity, and stylistic variation, making the language more vivid or better suited "
        "to a specific audience or context.\n\n"
        "Rewriting is different from polishing. Polishing focuses on minor improvements such as grammar correction and word optimization, "
        "while rewriting involves more substantial modifications — including rephrasing, changing tone, adjusting structure, and potentially "
        "reorganizing entire sections. You may use synonyms, reframe expressions, and strengthen or rephrase ideas, but you must preserve "
        "the original intent and meaning.\n\n"

        "I have a tweet that needs to be rewritten. Your task is to rewrite the text according to the above principles.\n\n"
        "Your rewriting needs to conform to the standards and expressions of tweets.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the rewritten text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the rewritten text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the rewritten content only."
    )
}

"""
expand operation
"""
expand_prompts={
    'xsum':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "Your rewriting needs to conform to the standards and expressions of news writing.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'writingprompts':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "Your rewriting needs to conform to the standards and expressions of creative writing.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'pubmedqa':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'squad':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'openreview':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "Your rewriting needs to conform to the standards and expressions of review comments.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'blog':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "Your rewriting needs to conform to the standards and expressions of blog writing.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    ),
    'tweets':(
        "Text expansion refers to the process where, given an input text, the language model generates new content that is closely related "
        "to the original but provides greater detail, richness, and expressed nuances. The goal is to make the original text more comprehensive, "
        "informative, and persuasive by adding relevant examples, elaborations, and new viewpoints, all while maintaining the original style and "
        "semantic coherence.\n\n"
        "Text expansion is different from text completion. Completion fills in missing parts of an unfinished text, while expansion adds new, meaningful "
        "information to an already complete text. It is also different from polishing, which only refines the surface expression. Expansion operates at "
        "the content level, enriching ideas and extending thought.\n\n"
        "Your task is to expand the following paragraph by introducing more details, examples, or perspectives while keeping the original meaning and tone intact. "
        "Avoid repeating information and ensure that the expansion maintains fluency and cohesion.\n\n"
        "Your rewriting needs to conform to the standards and expressions of tweets.\n\n"
        
        "The text is as follows:\n"
        "{context}\n\n"
        "Finally, only output the expanded text. "
        "Do not include any titles, explanations, or additional comments. "
        "Do not say anything like 'Here is the expanded text' or 'Sure here it is'. "
        "Do not return an empty string under any circumstances. "
        "Just return the expanded content only."
    )
}
